apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator.git
    path: example/prometheus-operator-crd
    targetRevision: v0.73.2
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    # automated: {}
