apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.9.0
    helm:
      releaseName: monitoring
      values: |
        # --- CRDs ---
        # Set true once (first install), false after.
        crds:
          enabled: false
        alertmanager:
          alertmanagerSpec:
            storageSpec: {} # use ephemeral emptyDir
        prometheus:
          prometheusSpec:
            storageSpec: {} # use ephemeral emptyDir

        grafana:
          persistence:
            enabled: false
        kube-state-metrics:
          enabled: true
        # # --- CRDs ---
        # # Set true once (first install), false after.
        # crds:
        #   enabled: false
        #
        # # --- Grafana ---
        # grafana:
        #   adminUser: admin
        #   adminPassword: admin
        #   service:
        #     type: ClusterIP
        #
        # # --- Prometheus ---
        # prometheus:
        #   prometheusSpec:
        #     retention: 2d
        #     storage:
        #       volumeClaimTemplate:
        #         spec:
        #           accessModes: ["ReadWriteOnce"]
        #           resources:
        #             requests:
        #               storage: 2Gi
        #           storageClassName: local-path
        #
        # # --- Alertmanager ---
        # alertmanager:
        #   alertmanagerSpec:
        #     storage: {}
        #     portName: web
        #
        # # --- Node Exporter / Metrics ---
        # prometheus-node-exporter:
        #   hostNetwork: false
        #   hostPort: false
        #
        # kube-state-metrics:
        #   enabled: true
        #
        # # --- Operator ---
        # prometheusOperator:
        #   createCustomResource: true
        #   admissionWebhooks:
        #     enabled: true
        #     patch:
        #       enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
