apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: {{ .Values.images.frontend }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: conf
          configMap:
            name: frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: html
          configMap:
            name: frontend-config
            items:
              - key: index.html
                path: index.html
