apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: { { .Values.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: react-frontend
          image: { { .Values.images.frontend } }
          ports:
            - containerPort: { { .Values.frontend.port } }
